apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: my-node-app:latest
        ports:
        - containerPort: 80
